config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'biografia', to: 'pages#biografia'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'defensa-paysandu-el-precio-de-una-traicion', to: 'pages#defensa_paysandu_el_precio_de_una_traicion'
  resources :slides
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :posts
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  validates :title, presence: true
  validates :year, presence: true
  has_one_attached :photo
  has_one_attached :cover
  has_rich_text :description
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     validate: true
  attribute :email,    validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,  validate: true
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nuevo mensaje desde tu sitio web",
      :to => ENV['GMAIL_USERNAME'],
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  friendly_id :title, use: :slugged
  validates :title, presence: true
  validates :content, presence: true
  has_one_attached :photo
  has_rich_text :content
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  friendly_id :title, use: :slugged
  validates :title, presence: true
  validates :description, presence: true
  has_one_attached :photo
  has_rich_text :description
end

app/models/slide.rb
class Slide < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  friendly_id :title, use: :slugged
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @books = Book.all.sort_by(&:year)
  end

  def show
    @book = Book.friendly.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
    @book = Book.friendly.find(params[:id])
  end

  def update
    @book = Book.friendly.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.friendly.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :year, :description, :awards, :subtitle, :slug, :link, :ebook_link, :booktrailer, :photo, :cover)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if verify_recaptcha(model: @contact)
       ContactMailer.contact_email(@contact).deliver_now
        @contact.request = request
        if @contact.deliver
           flash.now[:success] = 'Mensaje enviado'
         else
           flash.now[:error] = 'Imposible enviar mensaje'
           render :new
         end
    else
      render 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :biografia, :privacy_policy, :defensa_paysandu_el_precio_de_una_traicion]

  def home
    render "/slides/index"
    @slides = Slide.all
  end

  def biografia
  end

  def privacy_policy
  end

  def defensa_paysandu_el_precio_de_una_traicion
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @posts = Post.all.sort_by { |item| Date.strptime(item.date, '%d/%m/%Y') }.reverse
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :date, :content, :reference, :photo, :slug, :youtube_url)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @projects = Project.all.sort_by(&:year)
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.friendly.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :year, :description, :region, :trailer, :photo)
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @slides = Slide.all.sort_by(&:updated_at).reverse
  end

  def show
    @slide = Slide.friendly.find(params[:id])
  end

  def edit
    @slide = Slide.friendly.find(params[:id])
  end

  def update
    @slide = Slide.friendly.find(params[:id])
    @slide.update(slide_params)
    redirect_to root_path
  end

  private

  def slide_params
    params.require(:slide).permit(:title, :subtitle, :link, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/edit.html.erb
<h2 class="title">Modificar libro</h2>

<div class="input-wrapper">
  <div class="input">
    <%= simple_form_for (@book) do |p| %>
      <%= p.input :title, placeholder: 'Al encuentro de las Tres Marías', label: 'Título del libro' %>
      <%= p.input :subtitle, placeholder: 'Juana de Ibarbourou más allá del mito', label: 'Subtítulo del libro' %>
      <%= p.input :description, as: :rich_text_area, placeholder: 'Solapa del libro', label: 'Descripción' %>
      <%= p.input :year, placeholder: '2021', label: 'Año de publicación' %>
      <%= p.input :booktrailer, placeholder: 'Solo funciona YouTube', label: 'Trailer del libro' %>
      <%= p.input :ebook_link, placeholder: 'Link del eBook', label: 'Link de eBook' %>
      <%= p.input :link, placeholder: 'Link para comprarlo', label: 'Link para comprarlo' %>
      <%= p.input :photo, as: :file, required: false, label: 'Tapa del libro' %>
      <%= p.input :cover, as: :file, required: false, label: 'Foto para fondo' %>
     <div class="end"><%= p.submit 'Modificar libro', class: "btn" %> </div>
    <% end %>

  </div>
</div>

app/views/books/index.html.erb
<h2 class="title">Libros</h2>
<div class="everything">
  <div class="container">
    <% @books.reverse.each do |book| %>
      <%= link_to book_path(book) do %>
          <div class="mobile-layout">
            <div class="book-cover">

                  <% if book.photo.attached? %>
                  <%= cl_image_tag book.photo.key, class: 'book-top', width: 375, height: 269, crop: "scale" %>
                  <% else %>
                  <%= "" %>
                  <% end  %>

                <%= image_tag "book-side.svg", alt: "book-side", class: "book-side" %>
<!--            <img class="book-side" src="https://saranyamk.github.io/images-repo/book-side.svg" alt="book-side" /> -->
              </div>
            <div class="preface">
              <div class="content">
                <div class="header">
                  <div class="book_title"><%= book.title %></div>
                  </div>
                </div>
                <div class="subtitle"> <%= book.subtitle %></div>
                <div class="year"><%= book.year %></div>
              </div>
            </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to new_book_path do %>
        <h5 class="buy-btn admin">Agregar libro nuevo</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

app/views/books/new.html.erb
<h2 class="title">Nuevo libro</h2>

  <div class="input">

    <%= simple_form_for (@book) do |p| %>
      <%= p.input :title, required: true, placeholder: 'Al encuentro de las Tres Marías', label: 'Título del libro' %>
      <%= p.input :subtitle, placeholder: 'Juana de Ibarbourou más allá del mito', label: 'Subtítulo del libro' %>
      <%= p.input :description, required: true, as: :rich_text_area, placeholder: 'Solapa del libro', label: 'Descripción' %>
      <%= p.input :year, required: true, placeholder: '2021', label: 'Año de publicación' %>
      <%= p.input :booktrailer, placeholder: 'Solo funciona YouTube', label: 'Trailer del libro' %>
      <%= p.input :ebook_link, placeholder: 'Link del eBook', label: 'Link de eBook' %>
      <%= p.input :link, placeholder: 'Link para comprarlo', label: 'Link para comprarlo' %>
      <%= p.input :photo, as: :file, required: true, label: 'Tapa del libro' %>
      <%= p.input :cover, as: :file, required: true, label: 'Foto para fondo' %>
      <div class="end"><%= p.submit 'Agregar libro nuevo', class: "btn" %></div>
    <% end %>

  </div>

app/views/books/show.html.erb
<div class="cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @book.cover.key, height: 300, crop: :fill %>')"></div>

<div class="show-banner">
    <div class="libro">
      <span></span>
      <% if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, class: 'libro-img', alt: @book.title, width: 375, height: 269, crop: "scale" %>
      <% else %>
        <%= "" %>
      <% end  %>
    </div>

  <div class="show-title">
    <h1> <%= @book.title %></h1>
    <h3> <% if @book.subtitle %>
        <%= @book.subtitle %>
      <% else %>
        <%= "" %>
      <% end  %>
    </h3>
    <h4><%= @book.year %></h4>
    <div class="btn btn-group">
    <% if @book.link %>
      <a target="_blank" class="buy-btn" href="<%= @book.link %>"><h5>Comprar</h5></a>
    <% else %>
      <h5 class="buy-btn" style="pointer-events: none; cursor: not-allowed;">No disponible</h5>
    <% end %>
    <% if @book.ebook_link and @book.ebook_link != "" and @book.ebook_link != " " %>
      <a target="_blank" class="buy-btn" href="<%= @book.ebook_link %>"><h5>Comprar eBook</h5></a>
    <% else %>
      <h5 class="buy-btn" style="pointer-events: none; cursor: not-allowed;">No disponible en eBook</h5>
    <% end %>
  </div>
  </div>
</div>

<div class="description">
  <%= @book.description %>
</div>

  <% regex = /(?:v=)([^&]+)/  %>
  <% video_url = @book.booktrailer %>

<% unless video_url.nil? || video_url == "" || video_url == " " %>
<% video_match = video_url.match(regex) %>
  <div class="booktrailer">
      <iframe width="560" height="315"
      src="https://www.youtube.com/embed/<%= video_match[1] %>"
      title="<%= @book.title %> Book Trailer" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
      </iframe>
  </div>
<% end %>


<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to edit_book_path(@book) do %>
        <h5 class="buy-btn admin">Modificar libro</h5>
      <% end %>
      <%= link_to book_path(@book), method: :delete, data: { confirm: '¿Seguro que quieres borrar este libro?' } do %>
        <h5 class="buy-btn admin">Borrar libro</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

<% content_for :meta_title, "#{@book.title} de #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @book.description.to_plain_text  %>
<% content_for :meta_image, cl_image_path(@book.photo.key) %>

app/views/contacts/create.html.erb
  <h2 style="text-align: center;">Contacto</h2>

  <h4 style="text-align: center;">Gracias por tu contacto</h4>

app/views/contacts/new.html.erb
  <h2 style="text-align: center;">Contacto</h2>

 <div class="input">

  <%= simple_form_for (@contact) do |p| %>
      <%= p.input :name, placeholder: 'Nombre Apellido', label: 'Nombre', required: true %>
      <%= p.input :email, placeholder: 'nombre@gmail.com', label: 'Correo electrónico', required: true %>
      <%= p.input :message, as: :text, placeholder: 'Escribe aquí tu mensaje', label: 'Mensaje', required: true %>

       <%= recaptcha_tags %>

      <div class="end"><%= p.submit 'Enviar mensaje', class: "btn" %></div>
    <% end %>

</div>

app/views/layouts/_google_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=G-31HJYNVLJ5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-31HJYNVLJ5');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %> || Sitio web oficial</title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %> || Sitio web oficial" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %> || Sitio web oficial">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/google_analytics' %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <div class="container">
    <br>
    <% flash.each do |key, message| %>
      <p class="alert alert-<%= key %>"><%= message %></p>
    <% end %>
    </div>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/defensa_paysandu_el_precio_de_una_traicion.html.erb
  <div class="booktrailer">
      <iframe width="560" height="315"
      src="https://www.youtube.com/embed/or3rIzj2z84"
      title="El precio de una traición" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
      </iframe>
  </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/index.html.erb
<h2 class="title">Noticias</h2>

<div class="list">
    <% @posts.each do |post| %>
      <%= link_to post_path(post) do %>
        <div class="project_container">
          <i class="fas fa-signature"></i>
                <div class="project_text">
                  <div class="project_line"></div>
                  <div class="project_title">
                   <h3><%= post.title %></h3>
                    </div>
                  <div class="project_year">
                    <h5>
                      <%= post.date %>
                    </h5>
                    </div>
                </div>
          </div>
      <% end %>
    <% end %>

</div>

<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to new_post_path do %>
        <h5 class="buy-btn admin">Agregar noticia nueva</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

app/views/posts/show.html.erb
  <div class="show-title-project">
    <h1> <%= @post.title %></h1>
    <h4><%= @post.date %></h4>
    <div class="btn middle">
    <% if @post.reference %>
      <a class="buy-btn" href="<%= @post.reference %>"><h5>Ver publicación original</h5></a>
    <% else %>
      ''
    <% end %>
  </div>
  </div>

<div class="description">
  <%= @post.content %>
</div>

  <% regex = /(?:v=)([^&]+)/  %>
  <% video_url = @post.youtube_url %>

<% unless video_url.nil? || video_url == "" || video_url == " " %>
<% video_match = video_url.match(regex) %>
  <div class="booktrailer">
      <iframe width="560" height="315"
      src="https://www.youtube.com/embed/<%= video_match[1] %>"
      title="<%= @post.title %>" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
      </iframe>
  </div>
<% end %>

<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to edit_post_path(@post) do %>
        <h5 class="buy-btn admin">Modificar noticia</h5>
      <% end %>
      <%= link_to post_path(@post), method: :delete, data: { confirm: '¿Seguro que quieres borrar este proyecto?' } do %>
        <h5 class="buy-btn admin">Borrar noticia</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

<% content_for :meta_title, "#{@post.title} || #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @post.content.to_plain_text %>

app/views/projects/index.html.erb
<h2 class="title">Otros Proyectos</h2>

<div class="list">
    <% @projects.reverse.each do |project| %>
      <%= link_to project_path(project) do %>
        <div class="project_container">
                <div class="project_image">
                  <% if project.photo.attached? %>
                  <%= cl_image_tag project.photo.key, width: 375, height: 269, crop: "fill" %>
                  <% else %>
                  <%= "" %>
                  <% end  %>
                </div>
                <div class="project_text">
                  <div class="project_line"></div>
                  <div class="project_title">
                   <h3><%= project.title %></h3>
                  </div>
                  <div class="project_type">
                    <h4><%= project.region %></h4>
                  </div>
                  <div class="project_year">
                    <h5>
                      <%= project.year %>
                    </h5>
                  </div>
                </div>
          </div>
      <% end %>
    <% end %>

</div>

<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to new_project_path do %>
        <h5 class="buy-btn admin">Agregar proyecto nuevo</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

app/views/projects/show.html.erb
  <div class="show-title-project">
    <h1> <%= @project.title %></h1>
    <h3> <% if @project.region %>
        <%= @project.region %>
      <% else %>
        <%= "" %>
      <% end  %>
    </h3>
    <h4><%= @project.year %></h4>
  </div>

  <div class="project-image">
      <% if @project.photo.attached? %>
        <%= cl_image_tag @project.photo.key, class: "project_img", alt: @project.title, width: 1000, height: 500, crop: "fill", gravity: "auto" %>
      <% else %>
        <%= "" %>
      <% end  %>
  </div>

<div class="description">
  <%= @project.description %>
</div>

  <% regex = /(?:v=)([^&]+)/  %>
  <%  video_url = @project.trailer %>

<% unless @project.trailer.nil? || video_url == "" || video_url == " " %>
  <% project_match = video_url.match(regex) %>
  <div class="booktrailer">
      <iframe width="560" height="315"
      src="https://www.youtube.com/embed/<%= project_match[1] %>"
      title="<%= @project.title %>" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
      </iframe>
  </div>
<% end %>

<div class="admin-wrapper">
  <% if user_signed_in? %>
      <%= link_to edit_project_path(@project) do %>
        <h5 class="buy-btn admin">Modificar proyecto</h5>
      <% end %>
      <%= link_to project_path(@project), method: :delete, data: { confirm: '¿Seguro que quieres borrar este proyecto?' } do %>
        <h5 class="buy-btn admin">Borrar proyecto</h5>
      <% end %>
    <% else %>
    <div></div>
  <% end %>
</div>

<% content_for :meta_title, "#{@project.title} || #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @project.description.to_plain_text %>
<% content_for :meta_image, cl_image_path(@project.photo.key) %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="social">
    <a href="https://www.facebook.com/DiegoFischerAutor" target="_blank"><i class="fab fa-facebook-f"></i></a>
    <a href="https://www.instagram.com/diegofischer14/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.planetadelibros.com.uy/autor/diego-fischer/000054838" target="_blank"><i class="fas fa-book-open"></i></a>
    <a href="https://www.goodreads.com/author/show/2993049.Diego_Fischer" target="_blank"><i class="fab fa-goodreads-g"></i></a>
    <a href="https://www.amazon.es/Diego-Fischer/e/B001JOBMTE" target="_blank"><i class="fa-brands fa-amazon"></i></a>
    <%= link_to new_contact_path do %>
      <i class="far fa-envelope"></i></a>
    <% end %>
  </div>
  <div class="data"> <a href="mailto:info@diegofischer.com.uy" target="_blank">info@diegofischer.com.uy</a></div>
  <div class="data">
    © Copyright 2021 - <%= Time.zone.now.year %> Diego Fischer - Todos los derechos reservados.

    <%= link_to privacy_policy_path do %>
      Política de Privacidad
    <% end %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="site-header">
      <div class="wrapper site-header__wrapper">
        <a href="/" class="brand">
          <div class="name">DIEGO</div>
          <div class="surname">FISCHER</div>
        </a>
        <nav class="nav">

          <i class="fa fa-bars nav__toggle" aria-hidden="true" style="color: white; font-size: 1.5rem; padding-right: 20px;"></i>

          <ul class="nav__wrapper">
            <li class="nav__item">
              <%= link_to biografia_path do %>
                Biografía
              <% end %>
            <li class="nav__item">
              <%= link_to books_path do %>
                Libros
              <% end %>
            </li>
            <li class="nav__item">
              <%= link_to projects_path do %>
                Otros Proyectos
              <% end %>
            </li>
            <li class="nav__item">
              <%= link_to posts_path do %>
                Noticias
              <% end %>
            </li>
            <li class="nav__item">
              <%= link_to new_contact_path do %>
                Contacto
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </header>

app/views/slides/index.html.erb
<div class="slides">
  <%  Slide.all.sort_by(&:updated_at).reverse.each do |slide| %>
  <div class="slides-wrapper">
    <%= link_to slide.link do %>
    <div class="slide">
        <%= cl_image_tag slide.photo.key, class: "slide_image", alt: slide.title, crop: "fill", gravity: "auto" %>

      <div class="slide-text">
        <h2><%= slide.title %></h2>
        <h4><%= slide.subtitle %></h4>
      </div>
    </div>
    <% end %>
    <div class="admin-wrapper">
    <% if user_signed_in? %>
        <%= link_to edit_slide_path(slide) do %>
          <h5 class="buy-btn admin">Modificar slide</h5>
        <% end %>
      <% else %>
      <div></div>
    <% end %>
    </div>
   </div>
  <% end %>
</div>